"""fix typo

Revision ID: 1aaee6a4974f
Revises: 8bf69eb814aa
Create Date: 2025-08-17 08:12:11.730768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1aaee6a4974f'
down_revision: Union[str, Sequence[str], None] = '8bf69eb814aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog', sa.Column('author', sa.String(), nullable=False))
    op.drop_column('blog', 'auther')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog', sa.Column('auther', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('blog', 'author')
    # ### end Alembic commands ###
