"""update database table schema

Revision ID: 576b5c358b37
Revises: 1aaee6a4974f
Create Date: 2025-10-12 12:02:03.184386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '576b5c358b37'
down_revision: Union[str, Sequence[str], None] = '1aaee6a4974f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('blog', sa.Column('click', sa.BigInteger(), nullable=False))
    op.add_column('blog', sa.Column('deleted', sa.Boolean(), nullable=False))
    op.add_column('blog', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('blog', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('blog', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'blog', 'category', ['category_id'], ['id'], ondelete='SET NULL')
    op.drop_column('blog', 'author')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog', sa.Column('author', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'blog', type_='foreignkey')
    op.drop_column('blog', 'category_id')
    op.drop_column('blog', 'deleted_at')
    op.drop_column('blog', 'created_at')
    op.drop_column('blog', 'deleted')
    op.drop_column('blog', 'click')
    op.drop_table('category')
    # ### end Alembic commands ###
